packages:
  - 'packages/*'

catalog:
  '@biomejs/biome': ^1.9.4
  '@playwright/test': ^1.51.1
  '@rsbuild/core': ^1.3.1
  '@rslib/core': ^0.6.2
  '@types/node': ^22.8.1
  playwright: ^1.51.1
  typescript: ^5.8.3
  vitest: ^3.1.1
