packages:
  - packages/*
catalog:
  '@biomejs/biome': ^1.9.4
  '@playwright/test': ^1.51.1
  '@rsbuild/core': ^1.3.1
  '@rsbuild/plugin-react': ^1.2.0
  '@rslib/core': ^0.6.2
  '@types/node': ^22.8.1
  '@types/react': ^19.0.10
  '@types/react-dom': ^19.0.10
  playwright: ^1.51.1
  typescript: ^5.8.3
  vitest: ^3.1.1
  rslog: ^1.1.0
  type-fest: ^4.37.0
  ufo: ^1.3.0
  storybook: ^8.6.12
  storybook-addon-rslib: ^1.0.0
  storybook-react-rsbuild: ^1.0.0
  '@storybook/addon-essentials': ^8.6.12
  '@storybook/addon-interactions': ^8.6.12
  '@storybook/addon-links': ^8.6.12
  '@storybook/addon-onboarding': ^8.6.12
  '@storybook/blocks': ^8.6.12
  '@storybook/react': ^8.6.12
  '@storybook/test': ^8.6.12
  '@testing-library/react': ^13.4.0
  '@testing-library/jest-dom': 6.4.7
  jsdom: ^26.0.0
  react: ^19.0.0
  react-dom: ^19.0.0
  jiti: 1.21.7
  sharp: ^0.33.5
  ipx: ^3.0.3
  '@sindresorhus/is': ^7.0.1
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - core-js
  - esbuild
  - sharp
  - simple-git-hooks
