packages:
  - packages/*
  - e2e/fixtures/*
catalog:
  '@biomejs/biome': ^1.9.4
  '@playwright/test': ^1.51.1
  '@rsbuild/core': ^1.3.19
  '@rsbuild/plugin-react': ^1.3.1
  '@rslib/core': ^0.6.9
  '@types/node': ^22.8.1
  '@types/react': ^19.0.10
  '@types/react-dom': ^19.0.10
  playwright: ^1.51.1
  typescript: ^5.8.3
  vitest: ^3.1.1
  '@types/debug': ^4.1.12
  debug: ^4.4.0
  rslog: ^1.1.0
  type-fest: ^4.37.0
  ufo: ^1.3.0
  mlly: 1.7.4
  storybook: ^8.6.12
  storybook-addon-rslib: ^1.0.0
  storybook-react-rsbuild: ^1.0.0
  '@storybook/addon-essentials': ^8.6.12
  '@storybook/addon-interactions': ^8.6.12
  '@storybook/addon-links': ^8.6.12
  '@storybook/addon-onboarding': ^8.6.12
  '@storybook/blocks': ^8.6.12
  '@storybook/react': ^8.6.12
  '@storybook/test': ^8.6.12
  '@testing-library/react': ^13.4.0
  '@testing-library/jest-dom': 6.4.7
  jsdom: ^26.0.0
  react: ^19.0.0
  react-dom: ^19.0.0
  jiti: 1.21.7
  sharp: ^0.33.5
  ipx: ^3.0.3
  '@sindresorhus/is': ^7.0.1
  '@img/sharp-wasm32': ^0.33.5
  'rsbuild-plugin-publint': ^0.3.2
  'rspack-plugin-virtual-module': 1.0.0

catalogs:
  rspress:
    rspress: beta
    '@mdx-js/mdx': ^3.1.0
    '@rspress/shared': beta
    '@rspress/core': beta
    'estree-walker': ^3.0.3
    'mdast-util-mdx-jsx': ^3.2.0
    'mdast-util-mdxjs-esm': ^2.0.1
    'remark-gfm': ^4.0.1
    'unist-util-visit': ^5.0.0
    'typescript': ^5.8.2
    'unified': ^11.0.5
    '@types/mdast': ^4.0.4

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - core-js
  - esbuild
  - sharp
  - simple-git-hooks
